apiVersion: v1
kind: PersistentVolume
metadata:
  name: airflow-log
  labels:
    app: airflow-log
spec:
  storageClassName: manual

  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteMany
  claimRef:
    apiVersion: v1
    kind: PersistentVolumeClaim
    name: airflow-log
    namespace: airflow
  hostPath:
    path: /tmp/data/
