apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: airflow-log
  namespace: airflow
  labels:
    app: airflow-log
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 20Gi
